steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
artifacts:
  objects:
    location: 'gs://tiburon.doc.money'
    paths: ['build/**.json','build/**.png','build/**.json','build/**.html','build/**.js','static/css/**.css','static/js/**.js','media/**.svg','img/**.jpg']